function features = extract_HOG_features(img, cell_size, block_size, num_bins, block_overlap)
    % Extract HOG features from a single image
    
    % Extract HOG features using MATLAB's built-in function
    features = extractHOGFeatures(img, ...
        'CellSize', cell_size, ...
        'BlockSize', block_size, ...
        'NumBins', num_bins, ...
        'BlockOverlap', block_overlap);
end